### ISSUE TITLE
add mechanism to compute some part of statistics globally

### ISSUE THREAD

**Issue by piever** [JuliaPlots/StatsMakie.jl#27]
in `plot(StatsMakie.stack, histogram, Group(a), x)`. if different groups give different edges for the histogram, `StatsMakie` doesn't know how to stack it any more. There should be a mechanism to specify that the edges have to be computed globally.

**Comment by mkborregaard** [comment]
I wonder how ggplot2 does that. A sensible approach imho unless you had too many groups is to compute the correct bin number based on the global extrema / iqr but use the mean group n. Unfortunately all the bin computing is done in StatsBase now with no room for such pleasantries? @oschulz what about pr'ing those bin computation methods to StatsBase? Or, should the rather be ported to StatsMakie to allow such magic?

**Comment by mkborregaard** [comment]
On second thought, maybe not. Just generate the bins for the entire distribution as if it were one is a lot simpler and should work in practice.

**Comment by piever** [comment]
I think I'd rather avoid having non-trivial statistical operations live here. They should live in a statistical package (either StatsBase or another one). I'll probably go for binning the whole thing and passing the edges. It still requires a bit of care as  I don't currently have a mechanism for passing the whole column to the function `histogram` (other than just the "split" version) and would like to come up with a reasonably general mechanism. It's not too bad but a bit complicated by the fact that users may be passing curried versions of the initial function, so I need to think a bit about that.
